ALTER TABLE `BattleshipAttacks` DROP FOREIGN KEY `fk_BattleshipAttacks_BattleshipMatches`;
ALTER TABLE `BattleshipAttacks` DROP FOREIGN KEY `fk_BattleshipAttacks_Profiles`;
ALTER TABLE `BattleshipAttacks` DROP FOREIGN KEY `fk_BattleshipAttacks_BattleshipPositions`;
ALTER TABLE `BattleshipShipComponents` DROP FOREIGN KEY `fk_BattleshipShipComponents_BattleshipShips`;
ALTER TABLE `BattleshipShips` DROP FOREIGN KEY `fk_BattleshipShips_Profiles`;
ALTER TABLE `BattleshipShips` DROP FOREIGN KEY `fk_BattleshipShips_BattleshipPositions`;
ALTER TABLE `BattleshipShips` DROP FOREIGN KEY `fk_BattleshipShips_Teams`;
ALTER TABLE `BattleshipCells` DROP FOREIGN KEY `fk_BattleshipCells_BattleshipPositions`;
ALTER TABLE `BattleshipCells` DROP FOREIGN KEY `fk_BattleshipCells_Teams`;
ALTER TABLE `TeamLeaders` DROP FOREIGN KEY `fk_TeamLeaders_Profiles`;
ALTER TABLE `TeamLeaders` DROP FOREIGN KEY `fk_TeamLeaders_Teams`;
ALTER TABLE `Teams` DROP FOREIGN KEY `fk_Teams_BattleshipMatches`;
ALTER TABLE `BattleshipMatches` DROP FOREIGN KEY `fk_BattleshipMatches_Teams`;
ALTER TABLE `Profiles` DROP FOREIGN KEY `fk_Profiles_Teams`;
ALTER TABLE `Teams` DROP FOREIGN KEY `fk_Teams_Tables`;
ALTER TABLE `GameScores` DROP FOREIGN KEY `fk_GameScores_Locals`;
ALTER TABLE `GameScores` DROP FOREIGN KEY `fk_GameScores_Games`;
ALTER TABLE `Tables` DROP FOREIGN KEY `fk_Tables_Locals`;
ALTER TABLE `Tables` DROP FOREIGN KEY `fk_Tables_Beacons`;
ALTER TABLE `BattleshipNumberOfShots` DROP FOREIGN KEY `fk_BattleshipNumberOfShots_Profiles`;
ALTER TABLE `Profiles` DROP FOREIGN KEY `fk_Profiles_Beacons`;
ALTER TABLE `Profiles` DROP FOREIGN KEY `fk_Profiles_Sessions`;

DROP TABLE IF EXISTS `BattleshipAttacks`;
DROP TABLE IF EXISTS `BattleshipShipComponents`;
DROP TABLE IF EXISTS `BattleshipShips`;
DROP TABLE IF EXISTS `BattleshipPositions`;
DROP TABLE IF EXISTS `BattleshipCells`;
DROP TABLE IF EXISTS `TeamLeaders`;
DROP TABLE IF EXISTS `BattleshipMatches`;
DROP TABLE IF EXISTS `Teams`;
DROP TABLE IF EXISTS `GameScores`;
DROP TABLE IF EXISTS `Games`;
DROP TABLE IF EXISTS `Tables`;
DROP TABLE IF EXISTS `Locals`;
DROP TABLE IF EXISTS `BattleshipNumberOfShots`;
DROP TABLE IF EXISTS `Profiles`;
DROP TABLE IF EXISTS `Beacons`;
DROP TABLE IF EXISTS `Sessions`;
