SELECT 'GameScores';
SELECT * FROM `GameScores`;
SELECT 'Games';
SELECT * FROM `Games`;
SELECT 'BattleshipShipComponents';
#SELECT * FROM `BattleshipShipComponents`;
SELECT 'BattleshipShips';
SELECT * FROM `BattleshipShips`;
#SELECT 'BattleshipPositions';
#SELECT * FROM `BattleshipPositions`;
#SELECT 'BattleshipCells';
#SELECT * FROM `BattleshipCells`;
SELECT 'Tables';
SELECT * FROM `Tables`;
SELECT 'Locals';
SELECT * FROM `Locals`;
SELECT 'BattleshipAttacks';
SELECT * FROM `BattleshipAttacks`;
#SELECT 'Beacons';
SELECT * FROM `Beacons`;
SELECT 'Sessions';
SELECT * FROM `Sessions`;
SELECT 'Profiles';
SELECT * FROM `Profiles`;
SELECT 'TeamLeaders';
SELECT * FROM `TeamLeaders`;
SELECT 'BattleshipMatches';
SELECT * FROM `BattleshipMatches`;
SELECT 'Teams';
SELECT * FROM `Teams`;